import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.model_selection import KFold
from utils.metrics import calculate_metrics

def build_dnn_model(input_dim, lr=1e-4, dropout_rate=0.5): #function to build a dense neural network model with the specified input dimension, learning rate and dropout rate
    model = Sequential() #create a sequential model, which is a linear stack of layers
    model.add(Dense(64, input_dim=input_dim, activation='relu')) #add a dense layer with 64 units, ReLU activation function and the specified input dimension
    model.add(Dense(64, activation='relu')) #add another dense layer with 64 units and ReLU activation function
    model.add(Dropout(dropout_rate)) #add a dropout layer with the specified dropout rate to prevent overfitting
    model.add(Dense(1, activation='sigmoid')) #add an output layer with 1 unit and sigmoid activation function for binary classification
    model.compile(loss='binary_crossentropy',  #compile the model with binary cross-entropy loss function, Adam optimizer with the specified learning rate and accuracy as a metric
                  optimizer=tf.keras.optimizers.Adam(learning_rate=lr), 
                  metrics=['accuracy'])
    return model

def cross_validate_dnn(model, X, y, n_splits=5): #function to perform cross-validation for the dense neural network model, given the model, input data, target labels and number of splits for cross-validation
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42) #initialize KFold cross-validator with the specified number of splits, shuffling and random state for reproducibility
    metrics_list = [] 
    for train_index, val_index in kf.split(X): #iterate over the splits generated by KFold, obtaining the training and validation indices for each split
        X_train, X_val = X[train_index], X[val_index]
        y_train, y_val = y[train_index], y[val_index]
        model.fit(X_train, y_train, epochs=10, batch_size=16, verbose=0)
        y_val_pred = model.predict(X_val).ravel()
        metrics = calculate_metrics(y_val, y_val_pred)
        metrics_list.append(metrics)
    return metrics_list

def train_and_evaluate_dnn(model, X_train, y_train, X_test, y_test, model_file): #function to train the dense neural network model on the training data, save the trained model to a file and evaluate it on the test data, returning the calculated metrics and predicted probabilities for the test set
    model.fit(X_train, y_train, epochs=20, batch_size=16, verbose=0)
    model.save(model_file)
    y_test_pred = model.predict(X_test).ravel()
    metrics = calculate_metrics(y_test, y_test_pred)
    return metrics, y_test_pred