import pickle
from sklearn import svm, tree, naive_bayes, discriminant_analysis
from sklearn.ensemble import RandomForestClassifier # <--- AFEGIR AQUESTA LÍNIA
from xgboost import XGBClassifier
from sklearn.model_selection import KFold
from utils.metrics import calculate_metrics


def initialize_models(): #function to initialize the machine learning models that will be trained and evaluated in the pipeline, returning a dictionary with the model names as keys and the initialized model objects as values
    return {
        "BernoulliNB": naive_bayes.BernoulliNB(), 
        "DecisionTreeClassifier": tree.DecisionTreeClassifier(max_depth=3), 
        "SVC": svm.SVC(probability=True),
        "QuadraticDiscriminantAnalysis": discriminant_analysis.QuadraticDiscriminantAnalysis(reg_param=0.1),
        "RandomForestClassifier": RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42),
        "XGBClassifier": XGBClassifier(learning_rate=0.1, max_depth=3)
    }

def cross_validate_model(model, X, y, n_splits=5): #function to perform cross-validation for a given machine learning model, input data, target labels and number of splits for cross-validation, returning a list of metrics calculated for each fold
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
    metrics_list = []
    for train_index, val_index in kf.split(X): #iterate over the splits generated by KFold, obtaining the training and validation indices for each split
        X_train, X_val = X[train_index], X[val_index]
        y_train, y_val = y[train_index], y[val_index]
        model.fit(X_train, y_train)
        y_val_pred = model.predict_proba(X_val)[:, 1] if hasattr(model, "predict_proba") else model.predict(X_val)
        metrics = calculate_metrics(y_val, y_val_pred)
        metrics_list.append(metrics)
    return metrics_list

def train_and_evaluate_model(model, X_train, y_train, X_test, y_test, model_file): #function to train a given machine learning model on the training data, save the trained model to a file and evaluate it on the test data, returning the calculated metrics and predicted probabilities for the test set
    model.fit(X_train, y_train)
    with open(model_file, 'wb') as f: #save the trained model to a file using pickle
        pickle.dump(model, f)
    y_test_pred = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else model.predict(X_test)
    metrics = calculate_metrics(y_test, y_test_pred)
    return metrics, y_test_pred